POST http://localhost:3001/api/blogs/ 
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3R1c2VyMiIsImlkIjoiNjNkN2QyODc4NTBlNjY3OWM2MjdmZjYyIiwiaWF0IjoxNjc1MDkyNjE3fQ.NYhsrA5i2ALJRvdguR-Q7mogIyct8HSchr_qOHP7ygs

{
"title": "Blog3", 
"author": "Author3", 
"url": "www.blog3.com", 
"likes": 103
}